[workspace]
resolver = "2"
members = [
    "crates/kernel",
    "crates/hello",
    "crates/crash",
    "crates/catfile",
    "crates/wasmos-sys",
    "crates/sh",
    "crates/coreutils",
]

[workspace.package]
edition = "2021"
version = "0.0.0"
license = "MIT"

[profile.release]
opt-level = "s"
lto = true
strip = true
